// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button = ui_Button_create(ui_Screen1);
    lv_obj_set_width(ui_Button, lv_pct(30));
    lv_obj_set_height(ui_Button, lv_pct(20));
    lv_obj_set_x(ui_Button, 0);
    lv_obj_set_y(ui_Button, -3);

    ui_Label1 = lv_label_create(ui_Button);
    lv_obj_set_width(ui_Label1, lv_pct(100));
    lv_obj_set_height(ui_Label1, lv_pct(100));
    lv_obj_set_x(ui_Label1, 18);
    lv_obj_set_y(ui_Label1, 11);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Button");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}
